Subject: Test email 01
From: hailong552004@gmail.com
To: nguyenanhkhoi0608@gmail.com
Cc: tin75vn@gmail.com
Content-Type: multipart/mixed; boundary=vTwTC6bBYPV1EBw4

--vTwTC6bBYPV1EBw4
Content-Type: text/plain

This is a test email.


--vTwTC6bBYPV1EBw4
Content-Type:text/plain; charset=UTF-8; name="draft.txt"
Content-Disposition: attachment; filename="draft.txt"
Content-Transfer-Encoding: base64

VGhpcyBpcyBhIHNwYW0gZmlsZS4=
--vTwTC6bBYPV1EBw4
Content-Type:text/plain; charset=UTF-8; name="test.txt"
Content-Disposition: attachment; filename="test.txt"
Content-Transfer-Encoding: base64

VGhpcyBpcyBhIHZpcnVzIGZpbGUu

--vTwTC6bBYPV1EBw4--
